apiVersion: core.eda.nokia.com/v1
kind: Manifest
metadata:
  name: banners
spec:
  appInfo:
    categories:
      - uncategorised
  author: community
  dependencies:
    - file:
        path: utils
    - file:
        path: common
    - file:
        path: banners/intents
    - file:
        path: banners/api/v1alpha1/pysrc
  description: Sample description
  group: banners.eda.local
  image: ghcr.io/eda-labs/banners:v2.1.0
  supportedCoreVersions:
    - v2.0.0-0
  title: banners
  version: v1alpha1
  components:
    - crd:
        api:
          expose: readWrite
        path: banners/crds/banners.eda.local_banners.yaml
        schema: banners/openapiv3/eda_oas_banners.eda.local_banners.json
        ui:
          category: Banner
          name: Banner
    - script:
        path: banners/intents/banner/config_intent.py
        trigger:
          kind: Banner
        type: config
    - crd:
        path: banners/crds/banners.eda.local_bannerstates.yaml
        schema: banners/openapiv3/eda_oas_banners.eda.local_bannerstates.json
    - script:
        path: banners/intents/bannerstate/state_intent.py
        trigger:
          kind: BannerState
        type: state
  supportedEndpoints:
    - srl:0.0.0
    - srl:24.10.*
    - srl:25.*
    - sros:24.10.*
    - sros:25.*
